# Site settings
title: Disenone
header-img: "img/green.jpg"
tagline: "cn"  
description: "work smarter"  
baseurl: ""
url: "http://disenone.github.io"  

# About/contact
owner: 
  name: " Disenone"
  email: disenonec@gmail.com
  bio: "work smarter"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username: 145647322
twitter_username: 
github_username: disenone
facebook_username: 
weibo_username:  
zhihu_username: 

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Disenone"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshou
  duoshuo :
    short_name : disenone
  disqus :
      short_name : disenone

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation

gems: [jekyll-paginate]

permalink: /:year/:month/:day/:title 